### ISSUE TITLE
Add support for PHP 8.3

### ISSUE THREAD

**Issue by edwinbos** [Returnless-com/magento2#13]
With Magento 2.4.7 adding support for PHP 8.3, this module should also support this PHP version.

**Comment by chris-returnless** [comment]
Thanks Edwin, we have added support for PHP 8.3
Please note that Returnless v1 is reaching EOL, with 31-12-2024 being the last day that this platform is available.

We suggest the merchant to upgrade to Returnless V2 as soon as possible. For Returnless V2, a Magento extension is no longer required as we connect through the Magento REST API.
