### ISSUE TITLE
Add PHP 7.4 support

### ISSUE THREAD

**Issue by pepijnblom** [Returnless-com/magento2#2]
Magento 2.4 has been out for a while, when can we expect to see php 7.4 support?

**Comment by Returnless-com** [comment]
Hi Pepijn you are totally right. At this moment we are testing support for M2.4 and PHP 7.4 and we expect to release a newer version with some new features and this compatibility within a few weeks.

**Comment by arnoudhgz** [comment]
Bump :)

**Comment by arnoudhgz** [comment]
@Returnless-com  we have the module installed with M2.4.1, can the focus maybe be on only PHP 7.4?

**Comment by Returnless-com** [comment]
We've just completed some tests and verified that the extension works properly using PHP 7.4 + M2.4.1 and M.2.4.2.
We will add support in the composer.json with next release (which will be in a few days).

**Comment by Returnless-com** [comment]
We've released version [v1.0.7](https://github.com/Returnless-com/magento2/releases/tag/1.0.7) with compatibility for PHP 7.4. If you have any questions or issues please let us know. Thank you for your patience.
