### ISSUE TITLE
Calling undefined method

### ISSUE THREAD

**Issue by rasperen** [Returnless-com/magento2#3]
In Model/Api/OrderInfo.php in the constructor the logger is called with withName.
However, logger is a Psr\Log\LoggerInterface, which does not include a withName method.
Our implementation of the LoggerInterface doesn't include the withName method, which causes the retrieval of an order to fail.

**Comment by rasperen** [comment]
This problem is also located in Controller/Order/Info.php

**Comment by Returnless-com** [comment]
Hi @rasperen thank you for notifying us of this issue. If I understand correctly this error occurred after an update to Magento 2.4.2. We have a fix available to resolve this issue and will release a new version of the extension as soon as possible.

**Comment by Returnless-com** [comment]
Hi @rasperen we've released [v1.0.6](https://github.com/Returnless-com/magento2/releases/tag/1.0.6). Could you check if this release fixes your problem?
