### ISSUE TITLE
Add PHP 8.1 support

### ISSUE THREAD

**Issue by peterjaap** [Returnless-com/magento2#5]
For Magento 2.4.4

**Comment by chris-returnless** [comment]
Good point @peterjaap. Although we expect no issues with PHP 8.1, the connector is being tested for this version at the moment and we will add compatibility in the next release.

**Comment by chris-returnless** [comment]
We've released [version 1.2.3](
https://github.com/Returnless-com/magento2/releases/tag/1.2.3) of the Returnless Connector which is compatible with PHP 8.1. 

Thank you for your feedback.
